/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class AccessPoliciesOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
