/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gse.xtext.assignment.AccessPoliciesRuntimeModule;
import gse.xtext.assignment.AccessPoliciesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AccessPoliciesIdeSetup extends AccessPoliciesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AccessPoliciesRuntimeModule(), new AccessPoliciesIdeModule()));
	}
	
}
