/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.ide;


/**
 * Use this class to register ide components.
 */
public class AccessPoliciesIdeModule extends AbstractAccessPoliciesIdeModule {
}
