/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AccessPoliciesStandaloneSetup extends AccessPoliciesStandaloneSetupGenerated {

	public static void doSetup() {
		new AccessPoliciesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
