/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AccessPoliciesRuntimeModule extends AbstractAccessPoliciesRuntimeModule {
}
