/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import gse.xtext.assignment.accessPolicies.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Inject
	ValidationTestHelper validationHelper
	
	
	private def parseTest(String string, boolean valid) {
		val Model result = parseHelper.parse(string)
		if (valid) {
			Assertions.assertNotNull(result)			
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertTrue(errors.isEmpty, '''Parsing of "«string»" failed with unexpected errors: «errors.join(", ")»''')
			Assertions.assertTrue(issues.isEmpty, '''Parsing of "«string»" failed with unexpected issues: «issues.join(", ")»''')
		} else {
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertFalse(errors.isEmpty && issues.isEmpty, '''Unexpectedly parsed "«string»" which is invalid.''')
		}
	}	
	
	private def parseTest(String string) {
		parseTest(string, true);
	}

	// Simple declarations: actors, assets, and operations
	
	@Test
	def void parseActor() {
		parseTest('''
		player Novice
		''')
	}
	
	@Test
	def void parseActorsInherit() {
		parseTest('''
		player Novice
		player Knight inherits Novice
		''')
	}
	
	@Test
	def void parseActorsBadInherit() {
		parseTest('''
		player Novice
		player Knight inherits XXX
		''', false)
	}
	
	
	@Test
	def void parseAsset() {
		parseTest('''
		inventory BasicLoot
		''')
	}

	@Test
	def void parseAssets() {
		parseTest('''
		inventory BasicLoot
		inventory RareChest
		''')
	}
	
	@Test
	def void parseOperation() {
		parseTest('''
		event open
		''')
	}
	
	@Test
	def void parseActorAssetOperation() {
		parseTest('''
		player Novice
		event open
		inventory BasicLoot
		player GuildMaster inherits Novice
		''')
	}
	
	// Policies
	@Test
	def void parseEmptyPolicy() {
		parseTest('''
		guild_rules RaidAccess {
		}
		''')
	}
	@Test
	def void parsePolicyWithActor() {
		parseTest('''
		player Novice
		guild_rules RaidAccess {
			for_player Novice {
			}
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActors() {
		parseTest('''
		player Novice
		player Knight
		guild_rules RaidAccess {
			for_player Novice {
			}
			for_player Knight {
			}
		}
		''')
	}

	@Test
	def void parsePolicyWithActorAndRule() {
		parseTest('''
		player Novice
		inventory BasicLoot
		event open
		
		guild_rules RaidAccess {
		    for_player Novice {
		        allow open on BasicLoot
		    }
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActorAndRules() {
		parseTest('''
		player Novice
		inventory BasicLoot
		event open
		event equip
		
		guild_rules RaidAccess {
		    for_player Novice {
		        allow open on BasicLoot
		        forbid equip on BasicLoot
		    }
		}
		''')
	}
	
	@Test
	def void parseFullScenario() {
		parseTest('''
		// Actor hierarchy
		player Novice
		player Knight inherits Novice
		player GuildMaster inherits Novice
		
		// Assets
		inventory BasicLoot
		inventory RareChest
		
		// Operations
		event open
		event equip
		event trade
		
		// Security Policy
		guild_rules RaidAccess {
		    for_player Novice {
		        allow open on BasicLoot
		        forbid equip on BasicLoot
		    }
		
		    for_player Knight {
		        allow open on RareChest
		        forbid trade on RareChest
		    }
		
		    for_player GuildMaster {
		        allow equip on BasicLoot
		        allow trade on RareChest
		    }
		}
		''')
	}
	
}
