/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesCodeGenTest {

	@Inject extension CompilationTestHelper

	private def assertIsAllowed(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, true)
	}

	private def assertIsDenied(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, false)
	}

	private def assertIsAllowed(String code, String actor, String operation, String asset, boolean assertAllowed) {
		code.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			// Define a local helper lambda to simplify invocations
			val isAllowed = [ String myActor, String myOperation, String myAsset |
				isAllowedMethod.invoke(null, myActor, myOperation, myAsset) as Boolean
			]

			val boolean allowed = isAllowed.apply(actor, operation, asset)
			if (assertAllowed) {
				Assertions.assertTrue(allowed)
			} else {
				Assertions.assertFalse(allowed)
			}
		]

	}

	val String example = '''
		player Novice
		inventory BasicLoot
		event open
		
		guild_rules RaidAccess {
		    for_player Novice {
		        allow open on BasicLoot
		    }
		}
	'''

	// Simple declarations: actors, assets, and operations
	@Test
	def void testHasClassSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))
		]
	}

	@Test
	def void testCompilesSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			Assertions.assertNotNull(result.getCompiledClass("SecurityEvaluator"))
		]
	}

	@Test
	def void testHasMethodIsAllowed() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			Assertions.assertNotNull(isAllowedMethod)
		]
	}

	@Test
	def void testPositivePolicy() {
		assertIsAllowed(example, "Novice", "open", "BasicLoot")
	}

	@Test
	def void testPositivePolicyMultiple() {
		assertIsAllowed(example, "Novice", "open", "BasicLoot")
	}

	@Test
	def void testPositivePolicyWrongActor() {
		val code = '''
		player Novice
		player Knight
		inventory BasicLoot
		inventory RareChest
		event open
		
		guild_rules RaidAccess {
		    for_player Novice {
		        allow open on BasicLoot
		    }
		}
		guild_rules Data_Access {
		    for_player Knight {
		        allow open on RareChest
		    }
		}
		'''
		assertIsDenied(code, "Knight", "open", "BasicLoot")
		assertIsAllowed(code, "Novice", "open", "BasicLoot")
		
		assertIsDenied(code, "Novice", "open", "RareChest")
		assertIsAllowed(code, "Knight", "open", "RareChest")
	}

	@Test
	def void testInheritance() {
		val code = '''
			player Novice
			player Knight inherits Novice
			inventory BasicLoot
			event open
			event equip
			
			guild_rules RaidAccess {
			    for_player Novice {
			        allow open on BasicLoot
			    }
			}
		'''
		assertIsDenied(code, "Knight", "equip", "BasicLoot")
		assertIsAllowed(code, "Knight", "open", "BasicLoot")
	}

	@Test
	def void testInheritanceTransitive() {
		val code = '''
			player Novice
			player Knight inherits Novice
			player GuildMaster inherits Knight
			inventory BasicLoot
			event open
			event equip
			
			guild_rules RaidAccess {
			    for_player Novice {
			        allow open on BasicLoot
			    }		    
			}
		'''
		assertIsDenied(code, "GuildMaster", "equip", "BasicLoot")
		assertIsAllowed(code, "GuildMaster", "open", "BasicLoot")
	}

}

