/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class AccessPoliciesProposalProvider extends AbstractAccessPoliciesProposalProvider {
}
