/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AccessPoliciesScopeProvider extends AbstractAccessPoliciesScopeProvider {

}
