/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.generator

import gse.xtext.assignment.accessPolicies.Actor
import gse.xtext.assignment.accessPolicies.AllowRule
import gse.xtext.assignment.accessPolicies.Asset
import gse.xtext.assignment.accessPolicies.ForbidRule
import gse.xtext.assignment.accessPolicies.Model
import gse.xtext.assignment.accessPolicies.Operation
import gse.xtext.assignment.accessPolicies.PlayerScope
import gse.xtext.assignment.accessPolicies.Policy
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext



class AccessPoliciesGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val model = resource.contents.head as Model
		fsa.generateFile('SecurityEvaluator.java', 'TODO')
		fsa.generateFile('SecurityEvaluator.java', generateJava(resource.contents.head as Model))
	}

	dispatch def String generateJava(Model model) '''
		public class SecurityEvaluator {
			public static boolean isAllowed(String actor, String operation, String asset) {
				«FOR element : model.elements»
					«generatePolicyChecks(element)»
				«ENDFOR»
				return false;
			}

			private static boolean isActorOrInheritedFrom(String actor, String requiredActor) {
				if (actor == null || requiredActor == null) {
					return false;
				}
				if (actor.equals(requiredActor)) {
					return true;
				}
				«FOR element : model.elements»
					«generateInheritanceCheck(element)»
				«ENDFOR»
				return false;
			}
		}
	'''

	
	dispatch def String generatePolicyChecks(Actor actor) ''''''
	dispatch def String generatePolicyChecks(Asset asset) ''''''
	dispatch def String generatePolicyChecks(Operation operation) ''''''

	
	dispatch def String generatePolicyChecks(Policy policy) '''
		«FOR scope : policy.scopes»
			«generatePolicyChecks(scope)»
		«ENDFOR»
	'''

	dispatch def String generatePolicyChecks(PlayerScope scope) '''
		«FOR rule : scope.rules»
			«generatePolicyChecks(rule, scope)»
		«ENDFOR»
	'''

	
	dispatch def String generatePolicyChecks(AllowRule rule, PlayerScope scope) '''
		if (isActorOrInheritedFrom(actor, "«scope.actor.name»")
				&& "«rule.operation.name»".equals(operation)
				&& "«rule.asset.name»".equals(asset)) {
			return true;
		}
	'''

	
	dispatch def String generatePolicyChecks(ForbidRule rule, PlayerScope scope) ''''''

	
	dispatch def String generateInheritanceCheck(Actor actor) '''
		«IF actor.parent !== null»
			if ("«actor.name»".equals(actor)) {
				return isActorOrInheritedFrom("«actor.parent.name»", requiredActor);
			}
		«ENDIF»
	'''

	dispatch def String generateInheritanceCheck(Asset asset) ''''''
	dispatch def String generateInheritanceCheck(Operation operation) ''''''
	dispatch def String generateInheritanceCheck(Policy policy) ''''''

}