/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AccessPoliciesUiModule extends AbstractAccessPoliciesUiModule {

	public AccessPoliciesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
